### ISSUE TITLE
Sensor initialization doesn't work

### ISSUE THREAD

**Issue by MrXedac** [Apolline-Lille/apolline-flutter#1]
While on Android we can rely on a BluetoothGattCallback to perform initialization-related operations while ensuring the device is available when we want to do so, FlutterBlue doesn't seem to fully expose a lookalike API. 

While this might not be a problem with the iOS platform, Android doesn't queue pending operations and will just throw an error when the operation is not requested at the right time. 

Here is a partial stacktrace :
```I/flutter (14052): remoteId: 80:1F:12:B4:0E:6C characteristicUuid: 49535343-1e4d-4bd9-ba61-23c647249616 serviceUuid: 49535343-fe7d-4ae5-8fa9-9fafd205e455
E/flutter (14052): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(read_characteristic_error, unknown reason, may occur if readCharacteristic was called before last read finished., null)
E/flutter (14052): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14052): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (14052): <asynchronous suspension>
E/flutter (14052): #2      BluetoothCharacteristic.read (package:flutter_blue/src/bluetooth_characteristic.dart:83:10)
E/flutter (14052): #3      _SensorViewState.initializeDevice.<anonymous closure> (package:apollineflutter/sensor.dart:81:43)```

**Comment by MrXedac** [comment]
Seems like the problem doesn't originate from here. 
Currently no clues about where the problem lies

**Comment by MrXedac** [comment]
https://pub.dev/packages/flutter_ble_lib

**Comment by issaghaBarry** [comment]
l'utilisation d'un timer pour l'écriture corrige le souci
